### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by georgiamshaw** [craigargh/cfg-python#1]
Comparison is spelt 'conmparison' in the first line

https://github.com/craigargh/cfg-python/blob/master/more_depth/logic_and_if_statements.md

**Comment by Nirvikalpa108** [comment]
Hi @georgiamshaw @craigargh I can't find this spelling mistake anymore. Let me know if I'm just not looking properly or if we can close this issue! Thanks!

**Comment by craigargh** [comment]
I've moved the files around a lot in the last few months. It's now https://github.com/craigargh/cfg-python/blob/master/course_handbook/session_3.md

Thanks @georgiamshaw for spotting it. I must have missed the issue when you first created it
