### ISSUE TITLE
What is the difference between the raw_input function in Python 2 vs 3?

### ISSUE THREAD

**Issue by Nirvikalpa108** [craigargh/cfg-python#5]
Hi @craigargh, thanks very much for putting this course together. As I was attempting [Week 1 homework Question 3](https://github.com/craigargh/cfg-python/blob/master/homework/session_1.md#question-3), I had an error that only got solved once I used input() instead of raw_input() which I learnt about in the [Python docs](https://docs.python.org/3/whatsnew/3.0.html). I'm not sure if this is something only I will come across, but in case it isn't, do you think it's worth us adding some language to the question to help those attempting it that might come across this problem? If so, let me know and I can try drafting something that you can review. Thanks again, really grateful for all the work you've put into this!

**Comment by craigargh** [comment]
Thanks for pointing this out. The course used to written for Python 2.7, but has recently been updated to Python 3. `raw_input()` is from Python 2.7 and `input()` is Python 3. 

I didn't realise that it was here when I made the update. I've corrected it now.

I'll mention something in the session today as I didn't get around to doing `input()` during the session
